### ISSUE TITLE
LICENSE file is missing

### ISSUE THREAD

**Issue by rgommers** [attractivechaos/klib#149]
Hi, I'd like to request adding a license file to this repo. Right now most files have a header that says the license is `MIT`, and the README says `MIT/X11`, but there are also files without license headers (e.g. `keigen.c`) and just a sentence in the README isn't really enough.

Also, GitHub's license detection will say that Klib as a whole does not have a license: https://github.com/attractivechaos/klib/community

I'm happy to open a PR if that would help.

**Comment by rskinner** [comment]
Was just about to raise exactly this issue... The link to the explanation of what the MIT/X11 license is is not enough. Plus the linked article describes a number of variant MIT and X11 licenses - which doesn't provide any clarity at all

**Comment by jvriezen** [comment]
Related to this, why are there no recent 'Releases'?   My company is using Blackduck software and it is matching against klib-spawn-final release, even though I downloaded a recent Master branch which is much newer.   It would be better to have periodic releases with clear klib wide version numbers, so that we can be clear that our product is making use of klib version x.y.

**Comment by rgommers** [comment]
Thanks @attractivechaos

**Comment by jvriezen** [comment]
Was it your intent to leave the copyright year as '2008- ' without specifying a more recent year?
